config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pieces do
  	resources :bookings, only: [:new, :create, :delete, :edit, :update]
  end

  get 'profile', to: 'users#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :piece

end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, :price, :creation_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :pieces

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]


def index
	@booking = Booking.all
end

def new
  @piece = Piece.find(params[:piece_id])
	@booking = Booking.new
end

def create
    @piece = Piece.find(params[:piece_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.piece = @piece

    redirect_to root_path, notice: 'Votres reservation a bien été enregistrée'
end


def edit
end

def update
    @booking.update(booking_params)

    redirect_to piece_path(@booking)
end


def destroy
    @booking.destroy

    redirect_to bookings_path
end

private

  def booking_params

    params.require(:booking).permit(:date, :checkin, :checkout)

    # params.require(:piece).permit(:name, :price, :creation_date, :description)

  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home  
    if params[:query].present?
      @pieces = Piece.where(name: params[:query])
    else
      @pieces = Piece.all
    end
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :set_piece, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show]

  def index
    @user = current_user
    @pieces = current_user.pieces
  end

  def show
  end

  def new
    @piece = Piece.new
  end

  # def create
  #   @piece = Piece.new(params[:piece])
  #   @piece.save

  #   redirect_to piece_path(@piece)
  # end

  def create
    @piece = Piece.new(piece_params)
    @piece.user = current_user

    if @piece.save
      flash[:success] = "piece successfully created"
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
    redirect_to piece_path(@piece)
  end

  def edit
  end

  def update
    @piece.update(piece_params)

    redirect_to piece_path(@piece)
  end

  def destroy
    @piece.destroy
    redirect_to root_path
  end

  private

  def piece_params
    params.require(:piece).permit(:name, :price, :creation_date, :description, :photo_url)
  end

  def set_piece
    @piece = Piece.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  def profile
    @user = current_user
    @booked_pieces = current_user.bookings
    @pieces = current_user.pieces
    @bookings_by_other_user = Booking.where(piece: @pieces)
  end

def new
	@user = User.new
end

def create
    @user = User.new(User_params)
    @user.user = current_user

    if @user.save
        flash[:success] = "user successfully created"
        redirect_to user_path(@user)
    else
        flash[:error] = "Something went wrong"
        render 'new'
    end
end

def update
    @user.update(user_params)

    redirect_to user_path(@user)
end

def destroy
    @user.destroy

    redirect_to user_path
end

private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
blbajzjzfnzinfe

app/views/bookings/new.html.erb
<div class="container container-pieces max-height-100vh">
  <div class="new_booking">
    <h2>Nouvelle réservation 📆</h2>

  <%= simple_form_for [@piece, @booking] do |f| %>
    <h2>"<%= @piece.name %>"</h2>
    <h3><%= @piece.price %> € </h3>
    <%= f.input :checkin, placeholder: "checkin-date", as: :date%>
    <%= f.input :checkout, placeholder: "checkout-date", as: :date%>
    <%= f.submit "Réserver cette pièce", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container max-height-100vh">
  <h1>Bienvenue sur My MasterPiece 🎨<h1>

  <div class="">
  <%= form_tag root_path, method: :get, class:"d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a piece"%>
  <%= submit_tag "🔎", class: "btn " %>
<% end %>


  </div>


  <div class="row">
    <% @pieces.each do |piece| %>
      <%= render "shared/card_piece", piece: piece %>
    <% end %>
  </div>
</div>

app/views/pieces/_form.html.erb
  <%= simple_form_for(piece) do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :creation_date %>
    <%= f.input :description %>
    <%= f.input :photo_url, label: "Ton image" %>
    <%= f.submit %>
    <% end %>

app/views/pieces/edit.html.erb
<div class="container container-pieces max-height-100vh">
  <div class="edit-form">
    <%= render "form", piece: @piece %>
  </div>
</div>

app/views/pieces/index.html.erb
    <h1> Mes oeuvres 👨‍🎨 </h1>

<div class="container container-pieces max-height-100vh">



  <div class="row my-pieces">

      <% @pieces.each do |piece| %>
      <%= render "shared/card_piece", piece: piece %>
      <% end %>
  </div>
</div>

app/views/pieces/new.html.erb
  <div class="container container-pieces max-height-100vh">
    <div class="new-form">
        <h1> Ajouter mon oeuvre</h1>
      <%= render "form", piece: @piece %>
    </div>
  </div>

app/views/pieces/show.html.erb
<div class="container max-height-100vh">
  <div class="card card-show">
    <% if @piece.photo_url.present?  %>
    <%= image_tag @piece.photo_url %>
    <% else %>
    <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
    <% end %>
    <h1><%= @piece.name %></h1>
    <h2><%= @piece.price %>€</h2>
    <h4><%= @piece.creation_date %> After Jesus Death</h4>
    <p><%= @piece.description %></p>
    <div class="btn-show">
      <% if @piece.user == current_user %>
        <%= link_to "Delete", piece_path(@piece), method: :delete, class: "btn btn-info" %>
        <%= link_to "Edit", edit_piece_path(@piece), method: :get, class: "btn btn-info" %>
      <% else  %>
        <%= link_to "Booking",  new_piece_booking_path(@piece), method: :get, class: "btn btn-info" %>
    <% end %>
    </div>
  </div>
  <h4><%= link_to "Retour au menu", root_path %></h4>
</div>

app/views/shared/_card_piece.html.erb
<div class="art-card">
  <h3 class="art-piece-pricing"><%= piece.price%>€</h3>
  <% if piece.photo_url.present? %>
    <%= image_tag(piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
  <% else %>
  <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
  <% end %>
  <div class="art-piece-infos">
    <div>
      <h2><%= piece.name%></h2>
    </div>
   <h5><%= link_to "En savoir plus", piece_path(piece) %></h5>
  </div>
</div>

app/views/shared/_flashes.html.erb
      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
     <% end %>
     <% if alert %>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
     <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fab fa-youtube-square"></i></i></a>
  </div>
  <div class="footer-list">
    <ul>
      <li><a href="#">Nous contacter</a></li>
      <li><a href="#">On parle de nous</a></li>
      <li><a href="#">Notre histoire</a></li>
    </ul>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container max-height-100vh">
  <div class="Profil">
  <h1>Mon profil </h1>
  <h2>Mes oeuvres</h2>
    <div class="mes-infos">
      <%= @user.first_name %>
    </div>
    <div class="row">
      <% @pieces.each do |piece| %>
        <div class="profile-card">
          <h3 class="art-piece-pricing"><%= piece.price %> €</h3>
            <% if piece.photo_url.present? %>
            <%= image_tag(piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
            <% else %>
            <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
            <% end %>
            <div class="art-piece-infos">
              <h1><%= link_to piece.name, piece_path(piece) %></h1>
              <p><%= piece.description %></p>
            </div>
        </div>
      <% end %>
    </div>
        <h2>Réservations</h2>
    <div class="row">
      <% @bookings_by_other_user.each do |booking| %>
        <div class="profile-card">
          <h3 class="art-piece-pricing"><%= booking.piece.price %> €</h3>
          <% if booking.piece.photo_url.present? %>
            <%= image_tag(booking.piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
            <% else %>
            <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
            <% end %>
            <div class="art-piece-infos">
                <%# <h1><%= link_to piece.name, piece_path(piece) %>
                <h1><%= booking.piece.name  %></h1>
              <h4>Du <%= booking.checkin %> au <%= booking.checkout %></h4>
            </div>
        </div>
      <% end %>
    </div>
     <h2>Les oeuvres que j'ai réservé</h2>
      <div class="row">
        <% @booked_pieces.each do |booking| %>
        <div class="profile-card">
          <h3 class="art-piece-pricing"><%= booking.piece.price %> €</h3>
            <% if booking.piece.photo_url.present? %>
            <%= image_tag(booking.piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
            <% else %>
            <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
            <% end %>
          <div class="art-piece-infos">
              <div>
              <h1><%= booking.piece.name  %><h1>
              <h4>Du <%= booking.checkin %> au <%= booking.checkout %></h4>
              </div>
          </div>
        </div>
        <% end %>
      </div>
      <h4><%= link_to "Retour au menu", root_path %></h4>
   </div>
  </div>

app/views/users/show.html.erb
<div class="container max-height-100vh">
  <div class="Profil">
  <h1>Profil</h1>
  <h2>Mes oeuvres</h2>
    <div class="mes-infos">
      <%= @user.first_name %>
    </div>
    <div class="row">
      <% @pieces.each do |piece| %>
        <div class="profile-card">
          <h3 class="art-piece-pricing"><%= piece.price %> €</h3>
            <% if piece.photo_url.present? %>
            <%= image_tag(piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
            <% else %>
            <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
            <% end %>
            <div class="art-piece-infos">
              <h1><%= link_to piece.name, piece_path(piece) %></h1>
              <p><%= piece.description %></p>
            </div>
        </div>
      <% end %>
    </div>
        <h2>Oeuvres d'art réservées par d'autres personnes</h2>
    <div class="row">
      <% @bookings_by_other_user.each do |booking| %>
        <div class="profile-card">
          <h3 class="art-piece-pricing"><%= booking.piece.price %> €</h3>
          <% if booking.piece.photo_url.present? %>
            <%= image_tag(booking.piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
            <% else %>
            <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
            <% end %>
            <div class="art-piece-infos">
                <%# <h1><%= link_to piece.name, piece_path(piece) %>
                <h1><%= booking.piece.name  %></h1>
              <h4>Du <%= booking.checkin %> au <%= booking.checkout %></h4>
            </div>
        </div>
      <% end %>
    </div>
     <h2>Les oeuvres que j'ai réservé</h2>
      <div class="row">
        <% @booked_pieces.each do |booking| %>
        <div class="profile-card">
          <h3 class="art-piece-pricing"><%= booking.piece.price %> €</h3>
            <% if booking.piece.photo_url.present? %>
            <%= image_tag(booking.piece.photo_url,  alt: "artpiece1", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))") %>
            <% else %>
            <%= image_tag("paysage.jpg", :alt => "photo-paysage") %>
            <% end %>
          <div class="art-piece-infos">
              <div>
              <h1><%= booking.piece.name  %><h1>
              <h4>Du <%= booking.checkin %> au <%= booking.checkout %></h4>
              </div>
          </div>
        </div>
        <% end %>
      </div>
      <%= link_to "Retour au menu", root_path %>
   </div>
  </div>